"""empty message

Revision ID: 68990d5acb35
Revises: 0763d677d453
Create Date: 2025-09-19 22:50:29.786714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68990d5acb35'
down_revision = '0763d677d453'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
